package mhrq

import "math/big"

// Ciphertext represents a single encrypted record in the MHRQ scheme.
type Ciphertext struct {
	ID         string
	Keyword    string
	Op         string
	Value      int
	Timestamp  uint64
	ST         []byte
	PrevST     []byte
	Address    []byte
	Delta      []byte
	Token      []byte
	EncryptedP *Matrix
	Searchable bool
	IsRevoke   bool
}

// SearchResult is a decrypted/verified match returned by the server-side search.
type SearchResult struct {
	ID       string
	Keyword  string
	Value    int
	Matched  bool
	Trace    *big.Int
	CipherID string
}

// SetupParams captures the public parameters created during setup.
type SetupParams struct {
	N    int
	M1   *Matrix
	M2   *Matrix
	KSE  []byte
	KPRF []byte
}

// RevokeToken contains the refresh material generated by Revoke.
type RevokeToken struct {
	NewKPRF []byte
	MPrime  *Matrix
	MDPrime *Matrix
	Delta   []byte
	M3      *Matrix
	M4      *Matrix
}
